### ISSUE TITLE
AM2315 is not AM2315C sensor

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/AM2315#15]
(by email, abbreviated )

I am trying to use your library to interface with the ASAIR **AM2315C** sensor. I got the correct "AM2315_ADDRESS" which I updated into the header file & seems it recognize the i2c &  pullup 4.7k is also done. But its showing "AM2315_ERROR_CHECKSUM"  Can you please help me out for the same ?

----

1. I am using esp8266 dev board & supplied 5v to sensor & did pull up 4.7k using that same 5v 
2. Cable lengths from sensor to i2c is not more than 6-8inch 
3. If i comment out that crc check return statement from the header file it says ok but temperature shows a 320.0 static value & humidity shows nothing. Note that temperature value dose not change though I increase or decrease temperature. 

----

I already run the i2c scanner & found the different address that mentioned at your header file & I updated same address. Then it started saying crc error. If i use different address it says sensor not found. So i am confident here that my setup finds the i2c address & sensor itself 

----

 i found this i2c address 0x38 using i2c scanner. So i applied same to the library header.

**Comment by RobTillaart** [comment]
https://www.adafruit.com/product/5182

Here it is mentioned AM2315C is a different one from the AM2315.

https://github.com/RobTillaart/DHT20 might work for as it also has fixed 0x38 address (same sensor different package?)

**Comment by RobTillaart** [comment]
From AHT20 datasheet

![image](https://user-images.githubusercontent.com/462844/218305866-683f6b7c-83dd-4485-8039-09aefb7a55cd.png)


----

from DHT20 datasheet

![image](https://user-images.githubusercontent.com/462844/218306200-b64c85f2-445b-4ac9-adab-192f3058e6e1.png)

look pretty similar!

**Comment by RobTillaart** [comment]
Created https://github.com/RobTillaart/AM2315C

**Comment by fuzonmedia** [comment]
@RobTillaart thanks for your help. Its sorted using the DHT20 library. Many thanks

**Comment by RobTillaart** [comment]
@fuzonmedia 
Thanks for the support!
