### ISSUE TITLE
AM2315

### ISSUE THREAD

**Issue by JopWerff** [RobTillaart/AM2315#4]
Hoi Rob,

Your DHTNew is a very nice library and has advantages over the other DHT-libraries. I tested it with the DHT22.
I'm working with an ESP32,

For my real life project in the open air in conditions of rain and frost I would like to use a more robust version.
This one:
[https://www.tinytronics.nl/shop/nl/sensoren/lucht/vochtigheid/am2315-i2c-temperatuur-en-vochtigheidsmeter](url)

This complete product is using the **AM2315**, as you see.

But  I read in the specs for your DHTNew:
"Supports DHT11, DHT22, DHT33, DHT44, **AM2301**, **AM2302**, **AM2303** as these all have the same protocol."

You will understand my question now: is your fine library DHTNew also suitable for the **AM2315**?

 Kind regards,

    Jop

**Comment by RobTillaart** [comment]
AM2315 will be a new separate library as the low level protocol is really different from the DHT22 and alike.
(it might be compatible with other AM23xx devices)
- First testable version is now available - https://github.com/RobTillaart/AM2315
- The lib has no release yet, there is one simple test sketch added.
- The lib should support the ESP32,  might need change in pin numbers though

Give those folks at TT my regards, they know me. 
Tell them I'm working on a library for the AM2315 sensor, they might send me one :)

Please let me know your test result. 
Just a local test is good, does it give realistic values.

If you have other test sketches that might work as example, please send them over and I will add them to the lib.

**Comment by RobTillaart** [comment]
![image](https://user-images.githubusercontent.com/462844/148235938-2306ebcb-b2ac-4897-983f-3620fd764672.png)

**Comment by RobTillaart** [comment]
@JopWerff 
I move this discussion to the AM2315 library - https://github.com/RobTillaart/AM2315

**Comment by RobTillaart** [comment]
FYI - the automatic build (LINT) fails as the library is not registered yet at Arduino. 
(first test, then add release, then register)

**Comment by RobTillaart** [comment]
FYI, 
AM2320 I2C interface looks the same as AM2315  ( put on my wish list )

- http://akizukidenshi.com/download/ds/aosong/AM2320.pdf 

----
update: That means that my https://github.com/RobTillaart/AM232X library should work too. 
(and this lib is tested)

This lib does not have offset, but that is easy to add (working on it right now).

----
update
https://github.com/RobTillaart/AM232X (develop branch) is ready for testing..
- added offset humidity 
- added offset temperature
- added lastRead
- added ReadDelay

(fixed things in the AM2315 develop branch too)

**Comment by JopWerff** [comment]
Hoi Rob,

You are developing so fast.... I can't keep up.

Important thing to mention in your example(s): which pins (the numbers) I should use to connect the AM2315?

And if it is needed that I use other pin-numbers for I2C CLCK and DATA, how I will make this clear in initializing the library?

For now I want to use these numbers:
```
  #define AM2315_SCL_PIN 19 
  #define AM2315_SDA_PIN  5 

```
I got also the Idea (reading your link to the AM2320.PDF) that single bus is possible. Is this true?
Can you add an example?
For the DHT22 and your library DHTNew I used this pin:

`  #define DHTPIN 16    // Digital pin connected to the DHT sensor 

    DHTNEW mySensor(DHTPIN);
`

Late this afternoon I called TT and indeed your name was well known. They were glad to hear about your library development for the AM2315 (and equal types). I suggested the one at the phone (Mark) to provide you with a free AM2315. He was not the decision maker at TT but he proposed that you have to contact them yourself. I think you have to ask for Loek (or maybe Friso).
So that's my suggestion; no problem if you mention my name. 

I ordered this afternoon an AM2315 at TT. I hope this will arrive tomorrow, so I can test your developments.

Kind regards, 

    Jop

**Comment by RobTillaart** [comment]
you must add the pin numbers in the **begin()** call, something like 

```cpp
AM2315 sensor(&Wire);
...
sensor.begin(5, 19);  // DATA, CLOCK
```

> I got also the Idea (reading your link to the AM2320.PDF) that single bus is possible. Is this true?

not standard, you need an I2C multiplexer e.g. https://github.com/RobTillaart/TCA9548

Found an AM2322 to do some tests, ==> to be continued

**Comment by RobTillaart** [comment]
The AM2315 lib fails with the AM2322 - investigating...

Please try AM232X library first.

**Comment by RobTillaart** [comment]
solved with **setDisableIRQ(false)**. 
The interrupts suppression was needed for the DHT11/22 bitbang protocol. 
They are apparently needed to get I2C working correctly, so it needs to be removed.

**Comment by RobTillaart** [comment]
- Merged develop branche into master 
- Released 0.1.0
- Add library to Arduino registry

**Comment by JopWerff** [comment]
I am waiting now on my AM2315 sent from TT.

Did you contact TT to ask for an AM2315?
 I guess that's the best and easiest way to develop and test.

Regards,

   Jop

**Comment by JopWerff** [comment]
Hoi Rob,

This 

` sensor.begin(5, 19);  // DATA, CLOCK`

I guess this sensor.begin returns a boolean, indicating if an AM2315-sensor is connected and working?

**Comment by RobTillaart** [comment]
> Did you contact TT to ask for an AM2315? I guess that's the best and easiest way to develop and test.

I send a mail this morning I have published the library.

Having a sensor is the easiest (fastest) way to develop. I have worked in the past with remote testing on a Cozir sensor, a professional CO2 sensor, and yes there was substantial time between the iterations. Also with people living in other substantial other time zones give some delay.

**Comment by RobTillaart** [comment]
> I guess this sensor.begin returns a boolean, indicating if an AM2315-sensor is connected and working?

yes, should be stated in the readme ==> check ==> I see not explicit for the ESP version of begin ...
(created a documentation issue for this)

**Comment by JopWerff** [comment]
> I send a mail this morning I have published the library.

Yes, I've heard about when I called TT end afternoon. I spoke Mark again. I heard they were glad with your library and added already a link to it. Again I asked for a test AM2315 for you and Mark suggested again that you send your self a mail to TT to ask for an AM2315. It is of mutual interest that you can test the exact hardware and not a substitute.

Today I was too busy with other work; this weekend I will go on with AM2315 and your latest version library.

Thnx for all the work so far.

    Jop

**Comment by RobTillaart** [comment]
Thanks, 
Given that the datasheets were pretty exact the same I am confident it will work. 
The sensor is on my wish list for my next order, however family, work and other libraries need attention too, so low prio.

> this weekend I will go on with AM2315 and your latest version library.

Let me know if you have any troubles!

**Comment by JopWerff** [comment]
Hoi Rob,

Accidentally I came on this link, another library for the AM2315:
[https://forum.hobbycomponents.com/viewtopic.php?t=2418](url)

Maybe it brings you useful info. I didn't try this. Lack of time.

Good weekend,

     Jop

**Comment by RobTillaart** [comment]
Thanks, I'll have a look:

![image](https://user-images.githubusercontent.com/462844/148543225-aa0298cb-3859-4f10-9a25-e374e1ca78c8.png)

mmm. Apparently a bit proprietary. Won't spend time on it.

**Comment by JopWerff** [comment]
Hi Rob,

Did connect and test the new AM2315. 

But 
  if (sensor.begin(AM2315_SDA_PIN, AM2315_SCL_PIN)) {  // DATA, CLOCK`
returned false.

Here pin definitions:
```
#define AM2315_SCL_PIN 19 
#define AM2315_SDA_PIN  5

AM2315 sensor(&Wire);

```
I tried also with standard pins for SCL (22) and SDA (21) and same result.

When I ignore this returning of 'false' and let go program flow to the loop()
I get his output:

![CleanShot 2022-01-08 at 13 44 32@2x](https://user-images.githubusercontent.com/17315981/148644750-5c159b46-2eb8-4911-94cb-dd0788eecf33.png)

I hope you will receive your hardware  from TT soon.

Good weekend,

    Jop

**Comment by RobTillaart** [comment]
interesting alternating values.

Are the lines labeled OK reasonable temperatures and humidities?

you might try to increase the readdelay => setReadDelay(3000); 

TT order will be done coming week.

**Comment by JopWerff** [comment]
Yes, I think so. For the temperature values I'm more sure of it.

The daly between samples in loop() is now 2000 millis.

I added your suggestion and increased my loop()-delay to 10.000 millis.
Here the result:

![CleanShot 2022-01-08 at 17 07 08@2x](https://user-images.githubusercontent.com/17315981/148651255-c1de52f4-cb0f-437f-90e1-c7a6b8f596df.png)

Got worse by this.

But anyway the .begin() reports no sensor present. 
I have to ignore the result.

**Comment by RobTillaart** [comment]
> Got worse by this.

Not a solution but you could get back to the old timing and **setSuppressError(bool b)** to skip bad readings 

Other thought is to increase the frequency to 1 Hz.

I will check the datasheet if there is some sleep mode or so.

**Comment by RobTillaart** [comment]
From data sheet - par 7.2.1

![image](https://user-images.githubusercontent.com/462844/148651876-d09a0505-8268-49fd-917c-5d6ea1d3acf8.png)

Need to add a wake-up call and fix this in the **begin()** too.

Can you try adding a call to **isConnected()** after begin?
Does it return true?
(optionally add a short delay between begin() and isConnected().

**Comment by RobTillaart** [comment]
That paragraph explains the first log a bit, one call to wake the sensor, the other to read data.

(the good news is that the data can be extracted from the sensor)

**Comment by RobTillaart** [comment]
OK, the other library AM232X - has a different **isConnected()** function.  
That is used by **begin()** and by another function called **wakeUp()**.

Can you try that library / test sketch? 

If that **isConnected()** works, it will be an "easy fix".

**Comment by RobTillaart** [comment]
I created a develop branch with the possible fix included - https://github.com/RobTillaart/AM2315/tree/develop 

If time permits you may test it.

**Comment by RobTillaart** [comment]
Ordered the sensor @ TT, expect delivery on Tuesday => testing on Wednesday

**Comment by JopWerff** [comment]
Hoi Rob,

actually cannot spend now more time in this. The idea behind a library is that someone who is more skilled in such, should create a piece of software that we (other programmers) can see as a black box.... ;)
You are doing very useful work for us, for that reason I suggested TinyTronics to provide you with free hardware (and they are willing to do).

Just for curiosity I tested the Adafruit version and their test example, as I prepared this already in last week (before I received my AM2315). 
After improving first this weird code:
![CleanShot 2022-01-09 at 09 42 10@2x](https://user-images.githubusercontent.com/17315981/148675710-5c8871f7-e918-4fcc-bc07-aa2c23c10c9b.png)

**and after that I got this output:**
```
09:43:58.142 -> Perform AM2315 Test!
09:44:01.230 -> Failed to read data from AM2315
09:44:04.252 -> Temp *C: 14.40
09:44:04.252 ->   Hum %: 57.20
09:44:07.358 -> Failed to read data from AM2315
09:44:10.428 -> Failed to read data from AM2315
09:44:13.439 -> Temp *C: 14.40
09:44:13.439 ->   Hum %: 57.20
09:44:16.554 -> Failed to read data from AM2315
09:44:19.652 -> Failed to read data from AM2315
09:44:22.666 -> Temp *C: 14.40
09:44:22.666 ->   Hum %: 57.20
09:44:25.757 -> Failed to read data from AM2315
09:44:28.867 -> Failed to read data from AM2315
09:44:31.850 -> Temp *C: 14.40
09:44:31.850 ->   Hum %: 57.10
09:44:34.938 -> Failed to read data from AM2315
09:44:38.038 -> Failed to read data from AM2315
09:44:41.047 -> Temp *C: 14.40
09:44:41.047 ->   Hum %: 57.10


```
as you see your work for a new better library is very needed.

Have a good day,

  Jop

**Comment by RobTillaart** [comment]
> actually cannot spend now more time in this. 

OK, fair enough.

Apparently the Adafruit shows the same problem as my library.  
Thank you for testing as that is very informative.

So I wait until I have my sensor and time for testing the new branch with the **wakeUp()** code.
Will be Wednesday or later, if there is progress I will report here.

**Comment by JopWerff** [comment]
Thnx. Great!

I appreciate all your efforts.

(I have another issue I'm thinking "to bring on the table". A new type of sensor. You will read later about this - maybe we should start a new Issue for that - is such possible if there is not yet any software or a library connected to?

**Comment by RobTillaart** [comment]
Please open a new issue for it as it is not related. (mention type of sensor, and other relevant info).

You can do this under this library as I can move issues to the new library (or just create a placeholder repo).

**Comment by RobTillaart** [comment]
> is such possible if there is not yet any software or a library connected to?

Sure, 

Just got the message that the AM2315 sensor is expected tomorrow morning

**Comment by JopWerff** [comment]
Good to read. I hope you will solve the last problems we encountered.

**Comment by JopWerff** [comment]
Hoi Rob,

tomorrow we can ice skate again in Winterswijk. They are busy now  - this night - with preparing this natural ice. 

![image](https://user-images.githubusercontent.com/17315981/148842422-8620356d-e76e-4c3e-bb95-fcd4226d28a2.png)


And for this process I will use in the near future this AM2315 aside many other sensors.

Have a good night,

   Jop

**Comment by RobTillaart** [comment]
Good morning, looks like you can have a perfect temperature for an extra  layer of ice. Have fun.

**Comment by JopWerff** [comment]
Indeed, it's going quite well in the east of the Netherlands:
![image](https://user-images.githubusercontent.com/17315981/148893359-7b9c78ad-e206-4207-853b-5fa91f7a4eda.png)

My new issue, Rob, is a meter to measure the thickness of the ice layer.
And this should be a digital meter of course. So the samples can be a continuous stream of data to an ESP32/Arduino.

Now we are measuring the temperatures on different levels above, on and beneath the surface of the rink. 
These data can be used (not yet implemented) to control the flow of water to the spraying nozzles (when I have time I'll put a video of that process here with a link). The more severe the frost, the higher the flow of water can be. Also the humidity of the air plays an important role (for that reason the AM2315).

But the best and ultimate way to measure the effect of our spraying process would be: getting an idea of "is the ice layer growing or not"? If it grows, how fast it is growing?

As for the climate change we don't have the luxury anymore of many nights with -5℃ frost.  A more regular case is a frost that sometimes has a "dip". (temperature > 0℃). At such moment the spraying should stop immediately; otherwise we are  spooling or swilling with the sprayed water our just created ice layer away.
We like to know also: is the ice layer is growing fast or slow? If it looks like growing fast (and the frost we measure is more severe as the systeem can measure) we can increase the flow of water.

With good measuring of the growth of the ice layer we can develop a self-optimizing system. You see.

This is my first thought for our new issue.
Think about it.

Thnx, have a nice day. (o and go for ice skating today in Winterswijk - see [Winterswijkse IJs Vereniging](https://www.wijv.nl/)  WIJV .NL)

    Jop

![image](https://user-images.githubusercontent.com/17315981/148904840-78f0a0e9-38fb-4fe7-98c8-7d15ae59d885.png)

**Comment by RobTillaart** [comment]
First success with an Arduino UNO in the living room.

![image](https://user-images.githubusercontent.com/462844/148920424-e87229fe-19e0-490f-842c-2d07a8a5978b.png)

Values similar to a AM2320 and room thermostat (.8°C above but sensor is near laptop).

Time to read is approx 3.3 millisecond. 

I will upload this version to GIthub asap so you can verify it is working.

**Comment by JopWerff** [comment]
Ok, thnx Rob,

This looks much better! Today too busy, but I will try as soon as possible.

Success,

    Jop

**Comment by RobTillaart** [comment]
> This looks much better! Today too busy, but I will try as soon as possible.

OK.

I let him run for a few hours today and do some tests. to see if things pop up.

**next release**
There is a  delayMicroseconden(1500) in the code - (see datasheet) - and that value might be tunable in the next release. Now a acquisition takes 3.3 ms and it might be possible to bring it down to 2.5 or even 2.0 ms. 

Furthermore I am going to test the I2C clock frequency, Could also give some gain, maybe another ms. 
That does not look much but for RTOS environments every gain counts.

**Ice-thickness**
I understand the context, any specific sensor / technology in mind?

**Comment by JopWerff** [comment]
I wait until you give a signal that a new version AM2315 library can be updated.

IceThickness - yes I have a technology found (maybe) - later I will write more.

If you have an idea or found something in the area of mprocessor sensors, let me know.

**Comment by RobTillaart** [comment]
You can try the develop branch as I found no problems with it. 
It ran for an hour or so yesterday every 2 seconds with no failures.

About the Ice thickness you might mail me directly - see library.json

**Comment by RobTillaart** [comment]
released 0.1.1 - found no problems anymore today.

**Comment by JopWerff** [comment]
I got problems and very weird and not clear
I used the forked develop version 0.1.1

here some problems:
![CleanShot 2022-01-12 at 20 56 07@2x](https://user-images.githubusercontent.com/17315981/149293455-2072a686-b4ac-4b56-baf5-c0b6953549fb.png)

the weird thing, it has also a relation with the delay between the sampling calls

I will send you my sketch - based on your example - by mail (see the comments)

**Comment by RobTillaart** [comment]
Strange, not expected this 

With the unknown error it just repeats the last values

If time permits I will try to replicate the setup with a ESP32 today.
Do you power the sensor with 5V or 3V3?

**Comment by JopWerff** [comment]
now with 5V, before it was 3.3 but this was with your early version of the library. (and with the Adafruit-libr)

Shel I try with 3.3 again?

**Comment by RobTillaart** [comment]
First test ESP32

On 3V3 I got no data at all, on 5V I get output similar to yours
(investigation starts )

![image](https://user-images.githubusercontent.com/462844/149325452-c3982238-8e70-4f9f-a7e8-23c968a91265.png)

**Comment by RobTillaart** [comment]
TEST 1: AM232X library 
- AM232X uses same protocol (but slightly different implementation)
- default test example
- ESP32
- 5V power

![image](https://user-images.githubusercontent.com/462844/149325917-d9c977cf-9dae-4c7c-8d84-d310fde033ca.png)

So this works, now look at the diff in implementation.

**Comment by RobTillaart** [comment]
- wakeUp() code in both libraries is identical
- read() function differ a lot (AM2315 was adapted from DHTNEW 

TEST: adapt read() function to working AM232x version.

**Comment by RobTillaart** [comment]
"transplanted" the wakeUp part in the read() of the AM2315 library == Looks good!

![image](https://user-images.githubusercontent.com/462844/149328614-8881b4ff-aec7-44d2-810c-5bbaeca7de5f.png)

Now check next difference in timing.

**Comment by RobTillaart** [comment]
@JopWerff 

Looks slightly better as time between 2 read calls is closer to the 2.000 seconds.

![image](https://user-images.githubusercontent.com/462844/149329716-15d6476c-d73f-4445-b64d-7cf089b1652a.png)

I let it run for half an hour, clean up and prepare a new release, so you can test too.

**Comment by JopWerff** [comment]
ok, thnx

**Comment by RobTillaart** [comment]
@JopWerff 

All looks stable on ESP32, 
- develop branch pushed
- PR made

please verify if it works for you 

----
update:
- removed readDelay code as that is not tunable
- cleaned up code a bit.
- updated readme

**Comment by RobTillaart** [comment]
@JopWerff 
Short test 1 read per minute.

![image](https://user-images.githubusercontent.com/462844/149341950-b96de937-72e0-4f93-82b9-ca4fc6c0cf69.png)

Looks stable, I let the test run for some time.

**Comment by JopWerff** [comment]
What came up in my mind: wouldn't it be possible to create a possibility to switch off (and on) this automatic "go sleep" mode?
Of course for battery and solar charged situations this sleep mode is very useful. 

In my situation this "go sleep" is not necessary as all the m-processors (ESP32) are fed with continuous power. 
For test and demo modes I would disable the automatic "go sleep" mode and for regular use I would enable it (because as an ice skater I'm also worried about the climate change. - we shouldn't destroy our habitat - waiting so long on the next Elfstedentocht )

**Comment by RobTillaart** [comment]
The sensor itself shuts down to save energy, that is why the library needs a wake-up function.
As far as I know there is no switch to disable/enable it, The only way to overrule it is constant reading. 
(however there are several undocumented registers)



The one minute test still going strong.

16:30:01.230 -> AM2315, 	OK,	50.1,	19.2
16:31:01.248 -> AM2315, 	OK,	50.1,	19.2
16:32:01.226 -> AM2315, 	OK,	50.0,	19.2
16:33:01.235 -> AM2315, 	OK,	50.0,	19.2
16:34:01.260 -> AM2315, 	OK,	50.0,	19.2
16:35:01.257 -> AM2315, 	OK,	50.0,	19.2
16:36:01.258 -> AM2315, 	OK,	50.0,	19.2
16:37:01.225 -> AM2315, 	OK,	50.0,	19.2
16:38:01.241 -> AM2315, 	OK,	50.0,	19.2
16:39:01.272 -> AM2315, 	OK,	50.2,	19.1
16:40:01.242 -> AM2315, 	OK,	50.4,	19.2

**Comment by RobTillaart** [comment]
17:55:01.446 -> AM2315, 	OK,	49.0,	19.7
17:56:01.451 -> AM2315, 	OK,	49.0,	19.7
17:57:01.439 -> AM2315, 	OK,	49.0,	19.8
17:58:01.425 -> AM2315, 	OK,	49.0,	19.8
17:59:01.443 -> AM2315, 	OK,	48.9,	19.8
18:00:01.433 -> AM2315, 	OK,	49.0,	19.8


3.5 hrs no failure with ESP

**Comment by RobTillaart** [comment]
mmm, next test fails again

18:29:48.452 -> AM2315, 	Connect error,	-997.8,	-999.8
18:29:58.460 -> AM2315, 	Connect error,	-997.8,	-999.8

Had connected a 2nd I2C device and system fails. 
Not clear what is the cause...

**Comment by RobTillaart** [comment]
powerline error, fix and it works again 😀

20:00:06.511 -> AM2315, 	OK,	51.9,	20.2
20:00:16.541 -> AM2315, 	OK,	51.6,	20.2
20:00:26.547 -> AM2315, 	OK,	51.4,	20.2
20:00:36.534 -> AM2315, 	OK,	51.4,	20.2
20:00:46.529 -> AM2315, 	OK,	51.4,	20.2
20:00:56.542 -> AM2315, 	OK,	51.4,	20.2

1.5 hrs every 10 seconds no problemo. 

@JopWerff 
Going to dive in another project now, If you can confirm it works I will merge the 0.1.2 version into master

**Comment by JopWerff** [comment]
This is much better. It seems that all is ok. 
But wait until I've tested this also with other I2C pins dedicated, because that's my need in the end for my crowded ESP32-board.

Why is the Wire-library included?

As this code

```
#include <AM2315.h>
//#include "Wire.h"

AM2315 sensor(&Wire);

```
compiles also.

**Comment by RobTillaart** [comment]
That extra include is probably some leftover from testing. I check the code once again today to see if there are other minor edits to improve maintainability.

**Comment by RobTillaart** [comment]
0.1.2 released.
